### ISSUE TITLE
Doesn't seem to work?

### ISSUE THREAD

**Issue by yjeroen** [jtracey/journal-backlinks#3]
From what I understood: It should automatically link words in journals when the word corresponds to a different item/actor/journal, right?

![image](https://user-images.githubusercontent.com/1303988/162563006-ea742c28-635a-40c8-b749-af8a1c7c6fc9.png)

As you can see in my journal item called test, the text is not updated with links. I do see in the console that journal-backlinks is running on a journal save.

**Comment by jtracey** [comment]
If you go to the module settings and run "Sync now", does that populate it? (If you have a lot of entities, it might take a couple minutes.)

**Comment by yjeroen** [comment]
Apologies I should've been clear: I already tried that.

**Comment by jtracey** [comment]
Oh, I think there may be a misunderstanding for what this module does: it doesn't automatically add links to words, it makes it so that when you add a link, there is a section at the end that lists the things that links to this journal/actor/etc.. So if you add a link to from "gods" to "test", "test" will also have at the end a section linking back to "gods", and anything else that links to it.

**Comment by yjeroen** [comment]
Ah, I see! Thanks for explaining.

Automatic linking would be a great feature. ;)

**Comment by enigmafyv** [comment]
While the description says it "links" to items, I have an item that I've added to a journal, but the item description isn't updating with the link.  I have successfully linked two journals with this mod however.  Is there a system restriction as I'm using Earthdawn4e for my system?

**Comment by jtracey** [comment]
@enigmafyv It looks like there's a bug where the backlink on an item doesn't render if there's no description. If you put something in the description field of the item, does it work then?

**Comment by vexofp** [comment]
> It looks like there's a bug where the backlink on an item doesn't render if there's no description.

This behavior is the (intentional) result of the checks I added [here](https://github.com/jtracey/journal-backlinks/blob/c23a660d2e9f41af87c3d3511b109408f03badd3/scripts/journallink.js#L151), to work around a worse bug: If there was no content in the entry (journal, item, etc.), then when the TinyMCE editor opened it would populate with the back-links as if they were part of the entry (and thus when you saved you would end up with _two_ backlinks sections).

I was not able to find a better workaround at the time, but if anyone has an idea for solving that problem then it should be easy to re-enable back-links on empty entries.
